// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PhotoController from "./photo_controller"
import CarouselController from "./carousel_controller"

application.register("photo", PhotoController)
application.register("carousel", CarouselController)

