volumes:
  postgres-data:
    name: "diplom-postgres-data"

services:
  postgres:
    image: postgres:17.4-bullseye
    container_name: diplom-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  back:
    image: back:v1
    container_name: diplom-back
    restart: always
    ports:
      - "0.0.0.0:8080:3000"
    env_file:
      - .env