default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5423) %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", nil) %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", nil) %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", 'diplom_meh_development') %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", 'diplom_meh_development') %>

production:
  <<: *default
